### ISSUE TITLE
restTemplate报错：No instances available for localhost

### ISSUE THREAD

**Issue by cafe3165** [yinjihuan/spring-cloud#10]
ch3里面的eureka-client-article-service中的rest请求url不能用localhost，会报错，得改成项目名才能过，为什么？

>@GetMapping("/article/callHello") 	
	public String callHello() { 		
	    return restTemplate.getForObject(
			"http://eureka-client-user-service/user/hello", String.class);
	}

**Comment by yinjihuan** [comment]
你用localhost首先本地要有对应的接口才能调用，如果restTemplate加了@LoadBalanced就只能用服务名调用

**Comment by cafe3165** [comment]
> 你用localhost首先本地要有对应的接口才能调用，如果restTemplate加了@LoadBalanced就只能用服务名调用

嗯嗯，学了后面的知识才知道，谢谢啦~
