### ISSUE TITLE
找不到依赖

### ISSUE THREAD

**Issue by BruceKellan** [yinjihuan/spring-cloud#2]
我应该按照什么样的顺序依次mvn install?
另外，考虑将所有工程放在一个工程里面，对于看源代码的人更加友好一点

**Comment by yinjihuan** [comment]
目前所有代码就是在一个工程下啊，有个别的是依赖的别的库，在我github上都有的，你可以下载到本地就行了

**Comment by BruceKellan** [comment]
好的，谢谢
