### ISSUE TITLE
cxytiandi-jdbc在哪下载？

### ISSUE THREAD

**Issue by whatamazing** [yinjihuan/spring-cloud#4]
这个项目里不少地方都用到cxytiandi-jdbc，但是直接依赖是会报错的，请问这个在哪下载呢？

<dependency>
			<groupId>com.cxytiandi</groupId>
			<artifactId>cxytiandi-jdbc</artifactId>
			<version>1.0.1</version>
</dependency>

**Comment by yinjihuan** [comment]
https://github.com/yinjihuan/smjdbctemplate

**Comment by whatamazing** [comment]
thanks
