### ISSUE TITLE
《Spring Cloud微服务》入门，实战与进阶，第2章的源码spring-boot-starter-demo问题

### ISSUE THREAD

**Issue by tangyongshuang** [yinjihuan/spring-cloud#6]
spring-boot-starter-demo如果想被其他工程引用，需要达成jar包，存储在本地maven仓库中，但是给定的源码不能直接打包，主要是测试类报错和找不到主类的错误：

测试类和主类实际上都没必要，可以去掉，原工程中主类已经去掉，但是测试类未去掉；

解决办法：
1.删除测试类；
2.删掉如下插件，这个插件会去找你的Spring Boot主类，找不到会报错：
```
	<plugin>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-maven-plugin</artifactId>
	</plugin>
```
3.mvn clean install 本地仓库打包，就可以正常引用jar包了。

如有错误，感谢指正。

**Comment by yinjihuan** [comment]
感谢反馈，我编写案例的时候是直接在ide中引用的，没安装，所以没注意，直接去掉插件吧，这个属于依赖包，不需要启动类
