### ISSUE TITLE
从配置获取就不用在配置类中设值了吧

### ISSUE THREAD

**Issue by cafe3165** [yinjihuan/spring-cloud#9]
在code 2中ch2里的spring-boot-example中的TaskThreadPoolConfig线程池配置类，可以直接从配置文件中读取配置参数，而不用在这里设值
`   //核心线程数     
	private int corePoolSize;
`
`	//最大线程数     
private int maxPoolSize = 50;
`

**Comment by yinjihuan** [comment]
是的，我这只是示列，使用中通过配置更友好。

**Comment by cafe3165** [comment]
> 是的，我这只是示列，使用中通过配置更友好。

嗯嗯，明白了，谢谢
